name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Standup test stack
        run: docker-compose up -d

      - name: Give containers time to start
        run: sleep 30s
        shell: bash
      
      - name: Run integration tests
        run: npm run test:integration
      
      - name: Stop test stack
        if: always()
        run: docker-compose down
        
      - name: Build Nuget package
        run: dotnet pack --no-build --output nuget_output 

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.BDC_CI_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NUGET_GALLERY_TOKEN }}
          NUGET_PUSH_URL: ${{ secrets.NUGET_GALLERY_PUSH_URL }}
        run: npx semantic-release